from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^customerlogin', views.customerlogin, name="customerlogin"),
    url(r'^customerheader', views.customerheader, name="customerheader"),
    url(r'^customerhome', views.customerhome, name="customerhome"),
    url(r'^fordriver', views.fordriver, name="fordriver"),
    url(r'^bookdriver', views.bookdriver, name="bookdriver"),
    url(r'^confirmbookdriver', views.confirmbookdriver, name="confirmbookdriver"),
    url(r'^forcar', views.forcar, name="forcar"),
    url(r'^bookcar', views.bookcar, name="bookcar"),
    url(r'^confirmbookcar', views.confirmbookcar, name="confirmbookcar"),
    url(r'^forcab', views.forcab, name="forcab"),
    url(r'^bookcab', views.bookcab, name="bookcab"),
    url(r'^cstcardetails', views.cstcardetails, name="cstcardetails"),
    url(r'^cstconfirmbook', views.cstconfirmbook, name="cstconfirmbook"),
    url(r'^yourtrip', views.yourtrip, name="yourtrip"),
    url(r'^beowner', views.beowner, name="beowner"),
    url(r'^confirmowner', views.confirmowner, name="confirmowner"),
    url(r'^dsortR', views.dsortR, name="dsortR"),
    url(r'^dsortV', views.dsortV, name="dsortV"),
    url(r'^carsort', views.carsort, name="carsort"),
    url(r'^bookdriver', views.bookdriver, name="bookdriver"),
    url(r'^customerregister', views.customerregister, name="customerregister"),
    url(r'^creg', views.creg, name="creg"),
    url(r'^ddetails', views.ddetails, name="ddetails"),
    url(r'^chstcab', views.chstcab, name="chstcab"),
    url(r'^chstcar', views.chstcar, name="chstcar"),
    url(r'^chstdriver', views.chstdriver, name="chstdriver"),
    url(r'^cstcarreport', views.cstcarreport, name="cstcarreport"),
    url(r'^cstviewcars', views.cstviewcars, name="cstviewcars"),
    url(r'^cstrevert', views.cstrevert, name="cstrevert"),
    url(r'^cstallcars', views.cstallcars, name="cstallcars"),
    url(r'^thxaddcar', views.thxaddcar, name="thxaddcar"),
    url(r'^revertyes', views.revertyes, name="revertyes"),
    url(r'^revertno', views.revertno, name="revertno"),
    url(r'^customerforgotpass', views.customerforgotpass, name="customerforgotpass"),
    url(r'^customerresetpass', views.customerresetpass, name="customeresetpass"),
    url(r'^customercars', views.customercars, name="customercars")
]