# Generated by Django 3.0.2 on 2020-01-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminside',
            fields=[
                ('adminID', models.AutoField(primary_key=True, serialize=False)),
                ('adminUname', models.CharField(max_length=25)),
                ('adminFname', models.CharField(max_length=25)),
                ('adminLname', models.CharField(max_length=25)),
                ('adminPass', models.CharField(max_length=25)),
                ('adminPic', models.CharField(max_length=25)),
                ('adminCno', models.CharField(max_length=12)),
                ('adminEmail', models.EmailField(max_length=30)),
                ('adminDOB', models.DateField()),
                ('adminGender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customerside',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('customerUname', models.CharField(max_length=20)),
                ('customerFname', models.CharField(max_length=20)),
                ('customerLname', models.CharField(max_length=20)),
                ('customerPass', models.CharField(max_length=20)),
                ('customerPic', models.CharField(max_length=20)),
                ('customerDOB', models.DateField()),
                ('customerArea', models.CharField(max_length=20)),
                ('customerCity', models.CharField(max_length=20)),
                ('customerAddress', models.CharField(max_length=20)),
                ('customerGender', models.CharField(max_length=20)),
                ('customerEmail', models.EmailField(max_length=30)),
                ('customerDOJ', models.DateTimeField(auto_now_add=True)),
                ('customerVcnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driverside',
            fields=[
                ('driverID', models.AutoField(primary_key=True, serialize=False)),
                ('driverUname', models.CharField(max_length=25)),
                ('driverFname', models.CharField(max_length=25)),
                ('driverLname', models.CharField(max_length=25)),
                ('driverPass', models.CharField(max_length=25)),
                ('driverPic', models.CharField(max_length=25)),
                ('driverDOB', models.DateField()),
                ('driverGender', models.CharField(max_length=25)),
                ('driverArea', models.CharField(max_length=20)),
                ('driverCity', models.CharField(max_length=30)),
                ('driverAddress', models.CharField(max_length=50)),
                ('driverCno', models.CharField(max_length=12)),
                ('driverEmail', models.EmailField(max_length=30)),
                ('driverDOJ', models.DateTimeField(auto_now_add=True)),
                ('driverDOA', models.DateTimeField(auto_now_add=True)),
                ('driverRating', models.CharField(default=0, max_length=10)),
                ('driverVcnt', models.IntegerField()),
                ('driverAdhar', models.CharField(max_length=20)),
                ('driverIsAuth', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
