# Generated by Django 3.0.2 on 2020-02-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_cardetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('carName', models.CharField(max_length=30)),
                ('carCompany', models.CharField(max_length=20)),
                ('carType', models.CharField(max_length=30)),
                ('carCapacity', models.IntegerField()),
                ('carPic', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Cardetails',
        ),
        migrations.RenameField(
            model_name='driverside',
            old_name='driverAdhar',
            new_name='driverLicence',
        ),
    ]
