# Generated by Django 3.0.2 on 2020-02-05 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20200205_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='cID',
            new_name='carID',
        ),
        migrations.CreateModel(
            name='Cardetails',
            fields=[
                ('cdID', models.AutoField(primary_key=True, serialize=False)),
                ('cdFPKm', models.IntegerField(null=True)),
                ('cdFPH', models.IntegerField(null=True)),
                ('cdNumberplate', models.CharField(max_length=20)),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cars')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside')),
            ],
        ),
    ]
