# Generated by Django 3.0.2 on 2020-02-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20200205_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverside',
            name='driverFPH',
            field=models.CharField(default='', max_length=10),
        ),
    ]
