# Generated by Django 3.0.2 on 2020-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_driverside_driverfph'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerside',
            name='customerIsDriver',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerside',
            name='customerIsOwner',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customerside',
            name='customerStatus',
            field=models.CharField(default='', max_length=20),
        ),
    ]
