# Generated by Django 3.0.2 on 2020-02-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20200212_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerside',
            name='customerCno',
            field=models.CharField(default='', max_length=12),
        ),
    ]
