# Generated by Django 3.0.2 on 2020-02-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_customerside_customercno'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverside',
            name='customerID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside'),
        ),
    ]
