# Generated by Django 3.0.2 on 2020-02-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_driverside_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customerside',
            name='customerAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaID', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=20)),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.City')),
            ],
        ),
        migrations.AlterField(
            model_name='customerside',
            name='customerArea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Area'),
        ),
        migrations.AlterField(
            model_name='customerside',
            name='customerCity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.City'),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverArea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Area'),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverCity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.City'),
        ),
    ]
