# Generated by Django 3.0.2 on 2020-02-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20200213_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverside',
            name='driverCity',
        ),
    ]
