# Generated by Django 3.0.2 on 2020-02-14 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_remove_driverside_drivercity'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverside',
            name='driverCity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.City'),
        ),
    ]
