# Generated by Django 3.0.2 on 2020-02-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_driverside_drivercity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverside',
            name='driverArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Area'),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.City'),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverDOA',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverPic',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverRating',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverVcnt',
            field=models.IntegerField(default=0),
        ),
    ]
