# Generated by Django 3.0.2 on 2020-02-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20200214_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverside',
            name='customerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside'),
        ),
    ]
