# Generated by Django 3.0.2 on 2020-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_auto_20200215_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverside',
            name='driverFPH',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverVcnt',
            field=models.IntegerField(null=True),
        ),
    ]
