# Generated by Django 3.0.2 on 2020-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_auto_20200215_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverside',
            name='driverArea',
            field=models.IntegerField(),
        ),
    ]
