# Generated by Django 3.0.2 on 2020-02-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20200215_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverside',
            name='driverCity',
            field=models.IntegerField(),
        ),
    ]
