# Generated by Django 3.0.2 on 2020-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_auto_20200215_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverside',
            name='driverFPKm',
            field=models.IntegerField(null=True),
        ),
    ]
