# Generated by Django 3.0.2 on 2020-02-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_driverside_driverfpkm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerside',
            name='customerArea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerside',
            name='customerCity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customerside',
            name='customerCno',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='customerside',
            name='customerPic',
            field=models.CharField(default='', max_length=20),
        ),
    ]
