# Generated by Django 3.0.2 on 2020-02-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_auto_20200216_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerside',
            name='customerVcnt',
            field=models.IntegerField(null=True),
        ),
    ]
