# Generated by Django 3.0.2 on 2020-02-16 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_auto_20200216_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='carID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cars'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='cdNumberplate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
