# Generated by Django 3.0.2 on 2020-02-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_auto_20200216_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerside',
            name='customerIsDriver',
        ),
        migrations.RemoveField(
            model_name='customerside',
            name='customerStatus',
        ),
        migrations.RemoveField(
            model_name='driverside',
            name='customerID',
        ),
        migrations.AddField(
            model_name='driverside',
            name='driverIsOwner',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='Cabdriver',
            fields=[
                ('cabID', models.AutoField(primary_key=True, serialize=False)),
                ('cabFPKm', models.IntegerField(null=True)),
                ('carID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cars')),
                ('driverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Driverside')),
            ],
        ),
    ]
