# Generated by Django 3.0.2 on 2020-02-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_auto_20200229_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminside',
            name='adminPic',
            field=models.CharField(default='', max_length=25),
        ),
    ]
