# Generated by Django 3.0.2 on 2020-03-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20200229_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabdriver',
            name='cabIsAvailable',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Cabbooking',
            fields=[
                ('cabbookID', models.AutoField(primary_key=True, serialize=False)),
                ('cabDOBook', models.DateTimeField(auto_now_add=True)),
                ('cabEndTime', models.DateTimeField(null=True)),
                ('cabAmount', models.IntegerField(null=True)),
                ('cabStatus', models.CharField(default='', max_length=10)),
                ('cabID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cabdriver')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside')),
            ],
        ),
    ]
