# Generated by Django 3.0.2 on 2020-03-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_auto_20200313_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabdriver',
            name='cabdNumberplate',
        ),
    ]
