# Generated by Django 3.0.2 on 2020-03-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_remove_cabdriver_cabdnumberplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabdriver',
            name='cabNumberplate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
