# Generated by Django 3.0.2 on 2020-03-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_cabdriver_cabnumberplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='cabAproxEndTime',
            field=models.DateTimeField(null=True),
        ),
    ]
