# Generated by Django 3.0.2 on 2020-03-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_cabbooking_cabaproxendtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='cabID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='customerID',
            field=models.IntegerField(),
        ),
    ]
