# Generated by Django 3.0.2 on 2020-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_auto_20200314_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='cabDOBook',
            field=models.DateTimeField(null=True),
        ),
    ]
