# Generated by Django 3.0.2 on 2020-03-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_auto_20200314_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='cabID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cabdriver'),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='customerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside'),
        ),
    ]
