# Generated by Django 3.0.2 on 2020-03-16 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_auto_20200314_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carbooking',
            fields=[
                ('carbookID', models.AutoField(primary_key=True, serialize=False)),
                ('carDOBook', models.DateTimeField()),
                ('carEndTime', models.DateTimeField(null=True)),
                ('carAproxEndTime', models.DateTimeField()),
                ('carAmount', models.IntegerField(null=True)),
                ('carStatus', models.CharField(default='', max_length=10)),
                ('cdID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cardetails')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_use', to='admin_panel.Customerside')),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside')),
            ],
        ),
    ]
