# Generated by Django 3.0.2 on 2020-03-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_carbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='carDrop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Area'),
        ),
        migrations.AddField(
            model_name='carbooking',
            name='carPickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick', to='admin_panel.Area'),
        ),
    ]
