# Generated by Django 3.0.2 on 2020-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_auto_20200317_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='cdIsAvailable',
            field=models.CharField(default='', max_length=10),
        ),
    ]
