# Generated by Django 3.0.2 on 2020-03-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_cardetails_cdisavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverside',
            name='driverIsAvailable',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Driverbooking',
            fields=[
                ('driverBookID', models.AutoField(primary_key=True, serialize=False)),
                ('driverDOBook', models.DateTimeField()),
                ('driverEndTime', models.DateTimeField(null=True)),
                ('driverAproxEndTime', models.DateTimeField()),
                ('driverAmount', models.IntegerField(null=True)),
                ('driverStatus', models.CharField(default='', max_length=20)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside')),
                ('driverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Driverside')),
            ],
        ),
    ]
