# Generated by Django 3.0.2 on 2020-03-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_auto_20200317_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbooking',
            name='driverStartTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='driverDOBook',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='driverStatus',
            field=models.CharField(max_length=20),
        ),
    ]
