# Generated by Django 3.0.2 on 2020-03-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_auto_20200318_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='cabStartTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='cabAproxEndTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='cabDOBook',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='cabID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cabdriver'),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='cabStatus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cabbooking',
            name='customerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Customerside'),
        ),
    ]
