# Generated by Django 3.0.2 on 2020-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_auto_20200319_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabdriver',
            name='cabIsAvailable',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cabdriver',
            name='cabNumberplate',
            field=models.CharField(max_length=20),
        ),
    ]
