# Generated by Django 3.0.2 on 2020-03-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0038_auto_20200319_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='carStartTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cardetails',
            name='cdGodown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Area'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='carDOBook',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='carDrop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Area'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='carPickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick', to='admin_panel.Area'),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='carStatus',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='cdID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Cardetails'),
        ),
    ]
