# Generated by Django 3.0.2 on 2020-03-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0039_auto_20200320_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='cdGodown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Area'),
        ),
    ]
