# Generated by Django 3.0.2 on 2020-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_auto_20200320_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminside',
            name='adminGender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adminside',
            name='adminPic',
            field=models.ImageField(null=True, upload_to='static/adminimages'),
        ),
        migrations.AlterField(
            model_name='customerside',
            name='customerPic',
            field=models.CharField(default='customer.png', max_length=20),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverPic',
            field=models.CharField(default='driver.png', max_length=25),
        ),
    ]
