# Generated by Django 3.0.2 on 2020-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0041_auto_20200609_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminside',
            name='adminCno',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='adminside',
            name='adminEmail',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='adminside',
            name='adminPic',
            field=models.ImageField(null=True, upload_to='static/adminimages', verbose_name='adminPic'),
        ),
        migrations.AlterField(
            model_name='adminside',
            name='adminUname',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
