# Generated by Django 3.0.2 on 2020-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0042_auto_20200610_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerside',
            name='customerUname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverIsAuth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='driverside',
            name='driverIsAvailable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=20),
        ),
    ]
