# Generated by Django 3.0.2 on 2020-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0043_auto_20200612_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbooking',
            name='cabStatus',
            field=models.CharField(choices=[('book', 'book'), ('accepted', 'accepted'), ('start', 'start'), ('end', 'end')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cabdriver',
            name='cabIsAvailable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carbooking',
            name='carStatus',
            field=models.CharField(choices=[('book', 'book'), ('start', 'start'), ('end', 'end')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='cdIsAvailable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('reverted', 'reverted'), ('hold', 'hold'), ('given', 'given')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cars',
            name='carPic',
            field=models.ImageField(null=True, upload_to='static/carimages', verbose_name='carPic'),
        ),
        migrations.AlterField(
            model_name='driverbooking',
            name='driverStatus',
            field=models.CharField(choices=[('book', 'book'), ('accepted', 'accepted'), ('start', 'start'), ('end', 'end')], max_length=20),
        ),
    ]
